### ISSUE TITLE
lag issue when showing files tab ( Files [3] ) with 0.22.1

### ISSUE THREAD

**Issue by MartinVincent** [extrawurst/gitui#1451]
**Describe the bug**
When upgrading from 0.22.0 to 0.22.1, I noticed a lag when showing files tab (Files [3]), which was absent in 0.22.0.

**To Reproduce**

1.  Setup env: 
```~/Code ❯ git clone https://github.com/extrawurst/gitui.git
~/Code ❯ git clone https://github.com/extrawurst/gitui.git

Cloning into 'gitui'...
cd gitui
 ~/Code ❯ cd gitui/
 [master:ca19d42  ] ~/Code/gitui ❯ gitui_0.22.1 --version
gitui 0.22.1
```

2. Run gitui
3. Naviagte to tab 3: **Files[3]**
   - wait ~N seconds for files to show

**Expected behavior**
Expected the same behaviour as what was present in past versions: quasi instantaneous display of the files.

**Screenshots**
asciinema film/capture showing the difference between 0.22.0 and 0.22.1:
[![asciicast](https://asciinema.org/a/540141.svg)](https://asciinema.org/a/540141)

**Context (please complete the following information):**
 - Ubuntu 20.04.02 LTS
 - GitUI Version 0.22.1
 - cargo 1.60.0 (d1fd9fe 2022-03-01)

**Comment by extrawurst** [comment]
Please compare again via switching to the tab after the app start. In your comparison the app start mode hide the lag in 0.22.0.

because this is exactly what I addressed in https://github.com/extrawurst/gitui/commit/8e8c5fad5556d3b6e4afc9f127bf4f955a181287

**Comment by MartinVincent** [comment]
Hum, problem persists AFAICT: 

[![asciicast](https://asciinema.org/a/540152.svg)](https://asciinema.org/a/540152)

**Comment by extrawurst** [comment]
fixed. I forgot the debug code in there :(
